### ISSUE TITLE
[USECASE] AMQP-0.9

### ISSUE THREAD

**Issue by mrjingles** [asyncapi/event-gateway#158]
Hey guys, there seems to be not that much progress in the repository of the event gateway. As we are using RabbitMQ/AmazonMQ/AMQP-0.9 in our company I would like to get to know, if there is any plan to make to event gateway able to handle that as well?

Best regards,
Benjamin

**Comment by smoya** [comment]
@mrjingles the respository is not actively being developed. It was made as a POC, a validation experiment in order to see if we could make what we wanted. The experiment was positive, but we confirmed the big investment that requires in terms of investigation and work hours.
I would say I won't abandon it forever, but it is kinda for now. Still happy to help anyone that wants to keep evolving it.

**Comment by mrjingles** [comment]
@smoya Too bad. But thank you for giving me that update.
